#!/bin/bash

HDFS_RBF_DIRNAME=${PARCEL_DIRNAME:-"HDFS_RBF"}
export CDH_HADOOP_HOME=$PARCELS_ROOT/$HDFS_RBF_DIRNAME/lib/hdfs_rbf
export CDH_HADOOP_BIN=$PARCELS_ROOT/$HDFS_RBF_DIRNAME/bin
export HADOOP_CLASSPATH=/etc/hadoop/conf:$CDH_HADOOP_HOME:$CDH_HADOOP_HOME/lib/*:$CDH_HADOOP_HOME/*
