#!/bin/bash

HDFS_RBF_DIRNAME=${PARCEL_DIRNAME:-"HDFS_RBF"}
export CDH_HADOOP_HOME=$PARCELS_ROOT/$HDFS_RBF_DIRNAME/lib/hdfs_rbf
export CDH_HDFS_HOME=$CDH_HADOOP_HOME
export CDH_HDFS_BIN=$CDH_HDFS_HOME/bin/hdfs
